version: '3.9'

networks:
  dev_network:

services:

  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  mongo:
    image: mongo:4.4.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: 123
    depends_on:
      - redis
    networks:
      dev_network:
        aliases:
          - db-mongo
#  app:
#    build:
#      context: .
#    ports:
#      - "5050:5000"
#    container_name: app
#    depends_on:
#      - redis
#    networks:
#      dev_network:
#        aliases:
#          - flask
#    volumes:
#      - ./app:/app
